### ISSUE TITLE
FAQ ambiguity for IN_CLOSE_WRITE

### ISSUE THREAD

**Issue by ralienpp** [seb-m/pyinotify#55]
There is a tricky part in the FAQ that leaves room for interpretation:

> use IN_CLOSE_WRITE because if emitted **the all** changes on the appropriate file are safely written inside the file

Does it mean
1. if emitted, **all the** changes are safely inside the file
2. emitted **before** all the changes are safely inside the file

It seems to be the former, but I am experiencing a situation in which IN_CLOSE_WRITE is triggered, but when I open the file - it doesn't contain any changes yet. So I thought I would first make sure that I understand the manual correctly.

**Comment by estan** [comment]
> [...] but I am experiencing a situation in which IN_CLOSE_WRITE is triggered, but when I open the file - it doesn't contain any changes yet. So I thought I would first make sure that I understand the manual correctly.

@ralienpp This was over ten years ago, but I'm curious if you can remember which type of file system this was on. Because `write(2)` says

> POSIX requires that a read(2) that can be proved to occur after a write() has returned will return the new data.  Note that not all filesystems are POSIX conforming.

So what I'm thinking is that, since IN_CLOSE_WRITE fired, presumably all `write` calls have returned, so one should be able to rely on `read` seeing the written data.

So maybe you were using a file system that is not POSIX compliant in this regard...? Either that, or the writing side is calling close before all write calls have returned..?

Maybe I'm misunderstanding..

**Comment by ralienpp** [comment]
This was happening on Linux Mint (whatever the current version was at the time) running on ext3 with eCryptfs on top (which might have an impact on this behaviour).

**Comment by estan** [comment]
@ralienpp Thanks for the info! I may or may not research further what happened, just to satisfy my curiosity 😃
